/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: rudolfmato@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Ambulance
 */
export interface Ambulance {
    /**
     * Unique identifier of the ambulance
     * @type {string}
     * @memberof Ambulance
     */
    'id': string;
    /**
     * Human readable display name of the ambulance
     * @type {string}
     * @memberof Ambulance
     */
    'name': string;
    /**
     * 
     * @type {Array<WaitingListEntry>}
     * @memberof Ambulance
     */
    'waitingList'?: Array<WaitingListEntry>;
}
/**
 * 
 * @export
 * @interface WaitingListEntry
 */
export interface WaitingListEntry {
    /**
     * Unique id of the entry in this waiting list
     * @type {string}
     * @memberof WaitingListEntry
     */
    'id': string;
    /**
     * Name of inpatient room in waiting list
     * @type {string}
     * @memberof WaitingListEntry
     */
    'room'?: string;
    /**
     * Unique identifier of the patient known to Web-In-Cloud system
     * @type {string}
     * @memberof WaitingListEntry
     */
    'patientId'?: string;
    /**
     * Estimated duration of inpatient visit. If not provided then it will be computed based on condition and inpatient settings
     * @type {number}
     * @memberof WaitingListEntry
     */
    'capacity': number;
    /**
     * Estimated duration of inpatient visit. If not provided then it will be computed based on condition and inpatient settings
     * @type {number}
     * @memberof WaitingListEntry
     */
    'allocatedCapacity': number;
    /**
     * Estimated duration of inpatient visit. If not provided then it will be computed based on condition and inpatient settings
     * @type {number}
     * @memberof WaitingListEntry
     */
    'freeCapacity'?: number;
    /**
     * Estimated duration of inpatient visit. If not provided then it will be computed based on condition and inpatient settings
     * @type {number}
     * @memberof WaitingListEntry
     */
    'toPrepareCapacity'?: number;
}

/**
 * AmbulancesApi - axios parameter creator
 * @export
 */
export const AmbulancesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this method to initialize new ambulance in the system
         * @summary Saves new ambulance definition
         * @param {Ambulance} ambulance Ambulance details to store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAmbulance: async (ambulance: Ambulance, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulance' is not null or undefined
            assertParamExists('createAmbulance', 'ambulance', ambulance)
            const localVarPath = `/ambulance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ambulance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to delete the specific ambulance from the system.
         * @summary Deletes specific ambulance
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAmbulance: async (ambulanceId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('deleteAmbulance', 'ambulanceId', ambulanceId)
            const localVarPath = `/ambulance/{ambulanceId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * You get list of ambulances
         * @summary Provides the ambulances list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAmbulances: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ambulance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AmbulancesApi - functional programming interface
 * @export
 */
export const AmbulancesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AmbulancesApiAxiosParamCreator(configuration)
    return {
        /**
         * Use this method to initialize new ambulance in the system
         * @summary Saves new ambulance definition
         * @param {Ambulance} ambulance Ambulance details to store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAmbulance(ambulance: Ambulance, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Ambulance>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAmbulance(ambulance, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to delete the specific ambulance from the system.
         * @summary Deletes specific ambulance
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAmbulance(ambulanceId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAmbulance(ambulanceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * You get list of ambulances
         * @summary Provides the ambulances list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAmbulances(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Ambulance>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAmbulances(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AmbulancesApi - factory interface
 * @export
 */
export const AmbulancesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AmbulancesApiFp(configuration)
    return {
        /**
         * Use this method to initialize new ambulance in the system
         * @summary Saves new ambulance definition
         * @param {Ambulance} ambulance Ambulance details to store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAmbulance(ambulance: Ambulance, options?: any): AxiosPromise<Ambulance> {
            return localVarFp.createAmbulance(ambulance, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to delete the specific ambulance from the system.
         * @summary Deletes specific ambulance
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAmbulance(ambulanceId: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteAmbulance(ambulanceId, options).then((request) => request(axios, basePath));
        },
        /**
         * You get list of ambulances
         * @summary Provides the ambulances list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAmbulances(options?: any): AxiosPromise<Array<Ambulance>> {
            return localVarFp.getAmbulances(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AmbulancesApi - interface
 * @export
 * @interface AmbulancesApi
 */
export interface AmbulancesApiInterface {
    /**
     * Use this method to initialize new ambulance in the system
     * @summary Saves new ambulance definition
     * @param {Ambulance} ambulance Ambulance details to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulancesApiInterface
     */
    createAmbulance(ambulance: Ambulance, options?: AxiosRequestConfig): AxiosPromise<Ambulance>;

    /**
     * Use this method to delete the specific ambulance from the system.
     * @summary Deletes specific ambulance
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulancesApiInterface
     */
    deleteAmbulance(ambulanceId: string, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * You get list of ambulances
     * @summary Provides the ambulances list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulancesApiInterface
     */
    getAmbulances(options?: AxiosRequestConfig): AxiosPromise<Array<Ambulance>>;

}

/**
 * AmbulancesApi - object-oriented interface
 * @export
 * @class AmbulancesApi
 * @extends {BaseAPI}
 */
export class AmbulancesApi extends BaseAPI implements AmbulancesApiInterface {
    /**
     * Use this method to initialize new ambulance in the system
     * @summary Saves new ambulance definition
     * @param {Ambulance} ambulance Ambulance details to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulancesApi
     */
    public createAmbulance(ambulance: Ambulance, options?: AxiosRequestConfig) {
        return AmbulancesApiFp(this.configuration).createAmbulance(ambulance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to delete the specific ambulance from the system.
     * @summary Deletes specific ambulance
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulancesApi
     */
    public deleteAmbulance(ambulanceId: string, options?: AxiosRequestConfig) {
        return AmbulancesApiFp(this.configuration).deleteAmbulance(ambulanceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * You get list of ambulances
     * @summary Provides the ambulances list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AmbulancesApi
     */
    public getAmbulances(options?: AxiosRequestConfig) {
        return AmbulancesApiFp(this.configuration).getAmbulances(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * InpatientWaitingListApi - axios parameter creator
 * @export
 */
export const InpatientWaitingListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this method to store new entry into the waiting list.
         * @summary Saves new entry into waiting list
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {WaitingListEntry} waitingListEntry Waiting list entry to store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWaitingListEntry: async (ambulanceId: string, waitingListEntry: WaitingListEntry, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('createWaitingListEntry', 'ambulanceId', ambulanceId)
            // verify required parameter 'waitingListEntry' is not null or undefined
            assertParamExists('createWaitingListEntry', 'waitingListEntry', waitingListEntry)
            const localVarPath = `/waiting-list/{ambulanceId}/entries`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(waitingListEntry, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to delete the specific entry from the waiting list.
         * @summary Deletes specific entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWaitingListEntry: async (ambulanceId: string, entryId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('deleteWaitingListEntry', 'ambulanceId', ambulanceId)
            // verify required parameter 'entryId' is not null or undefined
            assertParamExists('deleteWaitingListEntry', 'entryId', entryId)
            const localVarPath = `/waiting-list/{ambulanceId}/entries/{entryId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)))
                .replace(`{${"entryId"}}`, encodeURIComponent(String(entryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * By using ambulanceId you get list of entries in inpatient waiting list
         * @summary Provides the inpatient waiting list
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWaitingListEntries: async (ambulanceId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('getWaitingListEntries', 'ambulanceId', ambulanceId)
            const localVarPath = `/waiting-list/{ambulanceId}/entries`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * By using ambulanceId and entryId you can details of particular entry item inpatient.
         * @summary Provides details about waiting list entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWaitingListEntry: async (ambulanceId: string, entryId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('getWaitingListEntry', 'ambulanceId', ambulanceId)
            // verify required parameter 'entryId' is not null or undefined
            assertParamExists('getWaitingListEntry', 'entryId', entryId)
            const localVarPath = `/waiting-list/{ambulanceId}/entries/{entryId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)))
                .replace(`{${"entryId"}}`, encodeURIComponent(String(entryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Use this method to update content of the waiting list entry.
         * @summary Updates specific entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {WaitingListEntry} waitingListEntry Waiting list entry to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWaitingListEntry: async (ambulanceId: string, entryId: string, waitingListEntry: WaitingListEntry, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('updateWaitingListEntry', 'ambulanceId', ambulanceId)
            // verify required parameter 'entryId' is not null or undefined
            assertParamExists('updateWaitingListEntry', 'entryId', entryId)
            // verify required parameter 'waitingListEntry' is not null or undefined
            assertParamExists('updateWaitingListEntry', 'waitingListEntry', waitingListEntry)
            const localVarPath = `/waiting-list/{ambulanceId}/entries/{entryId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)))
                .replace(`{${"entryId"}}`, encodeURIComponent(String(entryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(waitingListEntry, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InpatientWaitingListApi - functional programming interface
 * @export
 */
export const InpatientWaitingListApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InpatientWaitingListApiAxiosParamCreator(configuration)
    return {
        /**
         * Use this method to store new entry into the waiting list.
         * @summary Saves new entry into waiting list
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {WaitingListEntry} waitingListEntry Waiting list entry to store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createWaitingListEntry(ambulanceId: string, waitingListEntry: WaitingListEntry, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WaitingListEntry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createWaitingListEntry(ambulanceId, waitingListEntry, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to delete the specific entry from the waiting list.
         * @summary Deletes specific entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWaitingListEntry(ambulanceId: string, entryId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWaitingListEntry(ambulanceId, entryId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * By using ambulanceId you get list of entries in inpatient waiting list
         * @summary Provides the inpatient waiting list
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWaitingListEntries(ambulanceId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WaitingListEntry>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWaitingListEntries(ambulanceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * By using ambulanceId and entryId you can details of particular entry item inpatient.
         * @summary Provides details about waiting list entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWaitingListEntry(ambulanceId: string, entryId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WaitingListEntry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWaitingListEntry(ambulanceId, entryId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Use this method to update content of the waiting list entry.
         * @summary Updates specific entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {WaitingListEntry} waitingListEntry Waiting list entry to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateWaitingListEntry(ambulanceId: string, entryId: string, waitingListEntry: WaitingListEntry, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WaitingListEntry>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateWaitingListEntry(ambulanceId, entryId, waitingListEntry, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * InpatientWaitingListApi - factory interface
 * @export
 */
export const InpatientWaitingListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InpatientWaitingListApiFp(configuration)
    return {
        /**
         * Use this method to store new entry into the waiting list.
         * @summary Saves new entry into waiting list
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {WaitingListEntry} waitingListEntry Waiting list entry to store
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createWaitingListEntry(ambulanceId: string, waitingListEntry: WaitingListEntry, options?: any): AxiosPromise<WaitingListEntry> {
            return localVarFp.createWaitingListEntry(ambulanceId, waitingListEntry, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to delete the specific entry from the waiting list.
         * @summary Deletes specific entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWaitingListEntry(ambulanceId: string, entryId: string, options?: any): AxiosPromise<void> {
            return localVarFp.deleteWaitingListEntry(ambulanceId, entryId, options).then((request) => request(axios, basePath));
        },
        /**
         * By using ambulanceId you get list of entries in inpatient waiting list
         * @summary Provides the inpatient waiting list
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWaitingListEntries(ambulanceId: string, options?: any): AxiosPromise<Array<WaitingListEntry>> {
            return localVarFp.getWaitingListEntries(ambulanceId, options).then((request) => request(axios, basePath));
        },
        /**
         * By using ambulanceId and entryId you can details of particular entry item inpatient.
         * @summary Provides details about waiting list entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWaitingListEntry(ambulanceId: string, entryId: string, options?: any): AxiosPromise<WaitingListEntry> {
            return localVarFp.getWaitingListEntry(ambulanceId, entryId, options).then((request) => request(axios, basePath));
        },
        /**
         * Use this method to update content of the waiting list entry.
         * @summary Updates specific entry
         * @param {string} ambulanceId pass the id of the particular inpatient
         * @param {string} entryId pass the id of the particular entry in the waiting list
         * @param {WaitingListEntry} waitingListEntry Waiting list entry to update
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateWaitingListEntry(ambulanceId: string, entryId: string, waitingListEntry: WaitingListEntry, options?: any): AxiosPromise<WaitingListEntry> {
            return localVarFp.updateWaitingListEntry(ambulanceId, entryId, waitingListEntry, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InpatientWaitingListApi - interface
 * @export
 * @interface InpatientWaitingListApi
 */
export interface InpatientWaitingListApiInterface {
    /**
     * Use this method to store new entry into the waiting list.
     * @summary Saves new entry into waiting list
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {WaitingListEntry} waitingListEntry Waiting list entry to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApiInterface
     */
    createWaitingListEntry(ambulanceId: string, waitingListEntry: WaitingListEntry, options?: AxiosRequestConfig): AxiosPromise<WaitingListEntry>;

    /**
     * Use this method to delete the specific entry from the waiting list.
     * @summary Deletes specific entry
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {string} entryId pass the id of the particular entry in the waiting list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApiInterface
     */
    deleteWaitingListEntry(ambulanceId: string, entryId: string, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * By using ambulanceId you get list of entries in inpatient waiting list
     * @summary Provides the inpatient waiting list
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApiInterface
     */
    getWaitingListEntries(ambulanceId: string, options?: AxiosRequestConfig): AxiosPromise<Array<WaitingListEntry>>;

    /**
     * By using ambulanceId and entryId you can details of particular entry item inpatient.
     * @summary Provides details about waiting list entry
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {string} entryId pass the id of the particular entry in the waiting list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApiInterface
     */
    getWaitingListEntry(ambulanceId: string, entryId: string, options?: AxiosRequestConfig): AxiosPromise<WaitingListEntry>;

    /**
     * Use this method to update content of the waiting list entry.
     * @summary Updates specific entry
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {string} entryId pass the id of the particular entry in the waiting list
     * @param {WaitingListEntry} waitingListEntry Waiting list entry to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApiInterface
     */
    updateWaitingListEntry(ambulanceId: string, entryId: string, waitingListEntry: WaitingListEntry, options?: AxiosRequestConfig): AxiosPromise<WaitingListEntry>;

}

/**
 * InpatientWaitingListApi - object-oriented interface
 * @export
 * @class InpatientWaitingListApi
 * @extends {BaseAPI}
 */
export class InpatientWaitingListApi extends BaseAPI implements InpatientWaitingListApiInterface {
    /**
     * Use this method to store new entry into the waiting list.
     * @summary Saves new entry into waiting list
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {WaitingListEntry} waitingListEntry Waiting list entry to store
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApi
     */
    public createWaitingListEntry(ambulanceId: string, waitingListEntry: WaitingListEntry, options?: AxiosRequestConfig) {
        return InpatientWaitingListApiFp(this.configuration).createWaitingListEntry(ambulanceId, waitingListEntry, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to delete the specific entry from the waiting list.
     * @summary Deletes specific entry
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {string} entryId pass the id of the particular entry in the waiting list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApi
     */
    public deleteWaitingListEntry(ambulanceId: string, entryId: string, options?: AxiosRequestConfig) {
        return InpatientWaitingListApiFp(this.configuration).deleteWaitingListEntry(ambulanceId, entryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * By using ambulanceId you get list of entries in inpatient waiting list
     * @summary Provides the inpatient waiting list
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApi
     */
    public getWaitingListEntries(ambulanceId: string, options?: AxiosRequestConfig) {
        return InpatientWaitingListApiFp(this.configuration).getWaitingListEntries(ambulanceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * By using ambulanceId and entryId you can details of particular entry item inpatient.
     * @summary Provides details about waiting list entry
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {string} entryId pass the id of the particular entry in the waiting list
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApi
     */
    public getWaitingListEntry(ambulanceId: string, entryId: string, options?: AxiosRequestConfig) {
        return InpatientWaitingListApiFp(this.configuration).getWaitingListEntry(ambulanceId, entryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this method to update content of the waiting list entry.
     * @summary Updates specific entry
     * @param {string} ambulanceId pass the id of the particular inpatient
     * @param {string} entryId pass the id of the particular entry in the waiting list
     * @param {WaitingListEntry} waitingListEntry Waiting list entry to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InpatientWaitingListApi
     */
    public updateWaitingListEntry(ambulanceId: string, entryId: string, waitingListEntry: WaitingListEntry, options?: AxiosRequestConfig) {
        return InpatientWaitingListApiFp(this.configuration).updateWaitingListEntry(ambulanceId, entryId, waitingListEntry, options).then((request) => request(this.axios, this.basePath));
    }
}


