/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MrudInpatientWlList {
    }
}
declare global {
    interface HTMLMrudInpatientWlListElement extends Components.MrudInpatientWlList, HTMLStencilElement {
    }
    var HTMLMrudInpatientWlListElement: {
        prototype: HTMLMrudInpatientWlListElement;
        new (): HTMLMrudInpatientWlListElement;
    };
    interface HTMLElementTagNameMap {
        "mrud-inpatient-wl-list": HTMLMrudInpatientWlListElement;
    }
}
declare namespace LocalJSX {
    interface MrudInpatientWlList {
    }
    interface IntrinsicElements {
        "mrud-inpatient-wl-list": MrudInpatientWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mrud-inpatient-wl-list": LocalJSX.MrudInpatientWlList & JSXBase.HTMLAttributes<HTMLMrudInpatientWlListElement>;
        }
    }
}
